###
# List of methods/modules and their dependencies:
###
modules:
    - name: array_ops
    - name: assoc_rules
      depends: ['svec_util']
    - name: bayes
    - name: cart
      depends: ['utilities']
    - name: conjugate_gradient
      depends: ['array_ops']
    - name: convex
      depends: ['utilities']
    - name: crf
    - name: elastic_net
    - name: glm
      depends: ['utilities']
    - name: kernel_machines
      depends: ['svec_util']
    - name: kmeans
      depends: ['array_ops', 'svec_util', 'sample']
    - name: lda
      depends: ['array_ops']
    - name: linalg
    - name: linear_systems
      depends: ['utilities']
    - name: pca
      depends: ['linalg', 'convex']
    - name: pmml
    - name: prob
    - name: recursive_partitioning
      depends: ['utilities']
    - name: regress
      depends: ['utilities', 'array_ops']
    - name: sample
      depends: ['utilities', 'stats']
    - name: sketch
    - name: stats
      depends: ['array_ops']
    - name: summary
      depends: ['utilities', 'sketch']
    - name: svd_mf
    - name: svec
    - name: svec_util
      depends: ['svec']
    - name: tsa
    - name: utilities
      depends: ['linalg']
    - name: validation
      depends: ['array_ops', 'regress']
