###
# List of methods/modules and their dependencies:
###
modules:
    - name: array_ops
#    - name: assoc_rules
#      depends: ['svec']
    - name: bayes
    - name: compatibility
    - name: conjugate_gradient
      depends: ['array_ops']
    - name: data_profile
      depends: ['sketch']
#    - name: cart
    - name: kmeans
      depends: ['array_ops','svec']
    - name: kernel_machines
      depends: ['svec']
    - name: linalg
    - name: plda
    - name: prob
    - name: quantile
    - name: regress
#    - name: sample
    - name: sketch
    - name: stats
    - name: svd_mf
    - name: svec
    - name: utilities
      depends: ['linalg']
