#
# REQUIRED PARAMETERS:
#

# Name DB connection module for your platform
# Must be compliant with DB API 2.0.
# Tested: pygresql.pgdb, psycopg2
dbapi2: pygresql.pgdb
    
# According to DB API 2.0 specification
# allowed connection arguments:
#   dsn         Data source name as string
#   user        User name as string (optional)
#   password    Password as string (optional)
#   host        Hostname (optional)
#   database    Database name (optional)
connect_args:
    - host=localhost
    - database=testdb
    - user=gpadmin

# Name of your database schema to store MADlib objects    
target_schema: madlib

# List of MADlib methods
methods:
    - name: sketch
      port: pg_gp

    - name: profile
      port: pg_gp

    - name: bayes
      port: pg_gp

    - name: k-means
      port: pg_gp

    - name: kernel-machines
      port: pg_gp

    - name: regress
      port: pg_gp

    - name: svec
      port: pg_gp

    - name: svd-mf
      port: pg_gp

    - name: quantile 
      port: pg_gp
      
    - name: decision-tree
      port: pg_gp

    - name: conjugate-gradient
      port: pg_gp
      
#
# OPTIONAL PARAMETERS:
#

# Preprocessor macros for use in SQL files.
# For Conditional inclusion of lines, e.g. 
# depending on whether you're targeting Postgres or Greenplum.
# prep_flags: -DGREENPLUM

# Extension hook for post install actions.
# Name of a python script to run after standard installation.
# post_hook: greenplum.py
